name: Smoke Test

on:
  push:
    paths:
      - 'src/**'
      - 'resources/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'
      - '.gitignore'
      - '.github/workflows/smoke-test.yaml'
  workflow_dispatch:

concurrency:
  group: smoke
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust Dependency caching
        uses: Swatinem/rust-cache@v2
      - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: runner.os == 'Windows'
      - run: vcpkg install openssl:x64-windows-static-md
        if: runner.os == 'Windows'
      - name: Build it!
        run: cargo build --release